travis:
  secure:
    BINSTAR_TOKEN: bdoOpQrbRlFnghJmL9f8ktY+rrLy2gg63uWADQeXAwaV6E0pjxI+SyjdDrVYvk9VOLKqasqi5xRkqXHVa4cM7XybOu3dqHHWXvgqtbQjPgDamu+fOJ10cJzLDoslEplNCeza6xQzn/xYjNK+URngIXe1DGwwnlD93yal8n6LSl3cO4BGX7lVVrtPeofQ2YN/q1ZFyYhTKzobt3HTJO0EGRBmMdpD4p/7R2UiO5J09sb8Xd09P1kzSXwuQNWhTdme4my0Oj4SqM2UcmvNYphSNnrP0WFR3BOkBKMiB9njqxXbOTU33q3zoIW6akQelqSL6DHEZEpuA11eGXxaLSKUTO8zHNPlH8VdZx2mPkHOEqk5joJ5LtosmTkd3SjJq6P7sfGeP6DXFqu7oqBgfaWQIqi2M5hY4rae/wsRLotfrEYKEc0AeX9zCmbBg4u1PrVoLYss/ViDemUbpZ0rv4NljccUO//SmitGMCxVa5QsA7vzz2ywFXNzyge7Rjmdl9A1mdxipNWVzCat86/KX+/9FK7X/j6yoJ78OsVYGYDrpfYvdPm1BdGBvbDWn5biYWnpC+a9tI+D37PJBax2FX7TNreUlzIJjErZHP+lSk1RaCXs9YekU8XUx6Zc6aATalg5Cmf4jIrZfLNnYtUupO7hkcQJjIcWawM1uvKSf0mlFzI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
