travis:
  secure:
    BINSTAR_TOKEN: SNLnH0v0svHS8ZSZrxYzn1l9ANy86dQVHhM6bRmzhqsrwRPFevRKi/ScKWXyN82NxHt9xztvW0F+xuFvHcyoMfJ4dmXgd3rF2z+N8tKrxk8HhaL2T+RAGe/Xe8kUjq8pHXrp0oxRJsVMRMwgBdqCSswHH08k0jQPmRDvwGKfqeF/15vlmAf7lgQAywaV1zvqQ0UEfvGmZ76t5g04Kcw/AJ0aXd6KDrwUxaBnlmBO0mqMB4ZFFANgk8T+2goby6j9ryy1PTMuvPL+sle/ZHzyNHULXjHy7PmgrPSNCMm9+Gome1T55an/yW+PyzDGdgRqHbNDqxJGV8WDITVWg4UvnTUWLT/yif0YyHNIXgzZ8fRxi84bGYl2IJI0vlY4sSrrKcJHdP7DYClkMCxaIOFgxU21bbllaMbpLMUHX6ctHgcpygH1A180S7ahuQ4mbI1oFJmoesBhj/akwzbDjFFifuSO/zc30xkYOJ6BojmYQlLi2CGtsZCZvZDN7jbT4Np3d52X5sBn/DFN0sr2+J0QIuvxdjeqbuJubR8N+MQUgEkVaG8qlvMYBy13RGk+tU3kKi85NjYgiylK5kPD8uq8NrE7J9PQXhzdXiYu+oskZBipqJ+XbpmOAjyym84Jk9/PmuHKeWUui2YOSlWZ7j/LfmYVHQr6ZSwrTWxU1aa+jbs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
